// <auto-generated />
using System;
using Messzendzser.Model.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Messzendzser.Model.Migrations
{
    [DbContext(typeof(MySQLDbConnection))]
    [Migration("20221117111120_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("ChatroomAssociation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.Property<int>("ChatroomId")
                        .HasColumnType("int(11)")
                        .HasColumnName("chatroom_id");

                    b.HasKey("UserId", "ChatroomId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ChatroomId" }, "chatroom_id_idx");

                    b.HasIndex(new[] { "UserId" }, "user_id_idx");

                    b.ToTable("chatroom_associations", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("ChatroomUser", b =>
                {
                    b.Property<int>("ChatroomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatroomId", "UserId");

                    b.ToTable("ChatroomUser");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.Chatroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Icon")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("chatroom");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.ImageChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("ChatroomId")
                        .HasColumnType("int(11)")
                        .HasColumnName("chatroom_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("format");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_time");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatroomId" }, "image_chat_message_chatroom_id_idx");

                    b.HasIndex(new[] { "UserId" }, "image_chat_message_user_id_idx");

                    b.ToTable("image_chat_message");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.TextChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("ChatroomId")
                        .HasColumnType("int(11)")
                        .HasColumnName("chatroom_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_time");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatroomId" }, "chatroom_id_idx")
                        .HasDatabaseName("chatroom_id_idx1");

                    b.HasIndex(new[] { "UserId" }, "user_id_idx")
                        .HasDatabaseName("user_id_idx1");

                    b.ToTable("text_chat_message");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.VoiceChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("ChatroomId")
                        .HasColumnType("int(11)")
                        .HasColumnName("chatroom_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("format");

                    b.Property<int>("Length")
                        .HasColumnType("int(11)")
                        .HasColumnName("length");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_time");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatroomId" }, "voice_chat_message_chatroom_id_idx");

                    b.HasIndex(new[] { "UserId" }, "voice_chat_message_user_id_idx");

                    b.ToTable("voice_chat_message");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.VoipCredential", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.Property<string>("VoipPassword")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("voip_password");

                    b.Property<string>("VoipRealmHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("voip_realm_hash");

                    b.Property<string>("VoipUsername")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("voip_username");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("voip_credentials");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.Whiteboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("ChatroomId")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("chatroom_id");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("event");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.ToTable("whiteboard");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("ChatroomAssociation", b =>
                {
                    b.HasOne("Messzendzser.Model.DB.Models.Chatroom", null)
                        .WithMany()
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chatroom_associations_chatroom_id");

                    b.HasOne("Messzendzser.Model.DB.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chatroom_associations_user_id");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.ImageChatMessage", b =>
                {
                    b.HasOne("Messzendzser.Model.DB.Models.Chatroom", "Chatroom")
                        .WithMany("ImageChatMessages")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("image_chat_message_chatroom_id");

                    b.HasOne("Messzendzser.Model.DB.Models.User", "User")
                        .WithMany("ImageChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("image_chat_message_user_id");

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.TextChatMessage", b =>
                {
                    b.HasOne("Messzendzser.Model.DB.Models.Chatroom", "Chatroom")
                        .WithMany("TextChatMessages")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("text_chat_message_chatroom_id");

                    b.HasOne("Messzendzser.Model.DB.Models.User", "User")
                        .WithMany("TextChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("text_chat_message_user_id");

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.VoiceChatMessage", b =>
                {
                    b.HasOne("Messzendzser.Model.DB.Models.Chatroom", "Chatroom")
                        .WithMany("VoiceChatMessages")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("voice_chat_message_chatroom_id");

                    b.HasOne("Messzendzser.Model.DB.Models.User", "User")
                        .WithMany("VoiceChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("voice_chat_message_user_id");

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.VoipCredential", b =>
                {
                    b.HasOne("Messzendzser.Model.DB.Models.User", "User")
                        .WithOne("VoipCredential")
                        .HasForeignKey("Messzendzser.Model.DB.Models.VoipCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("voip_credentials_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.Chatroom", b =>
                {
                    b.Navigation("ImageChatMessages");

                    b.Navigation("TextChatMessages");

                    b.Navigation("VoiceChatMessages");
                });

            modelBuilder.Entity("Messzendzser.Model.DB.Models.User", b =>
                {
                    b.Navigation("ImageChatMessages");

                    b.Navigation("TextChatMessages");

                    b.Navigation("VoiceChatMessages");

                    b.Navigation("VoipCredential");
                });
#pragma warning restore 612, 618
        }
    }
}
